### ISSUE TITLE
option to install/remove

### ISSUE THREAD

**Issue by symbios24** [retr0rangepi/RetrOrangePi#17]
Hello,great work

Is it possible to add to the script option/s to install/remove Quake 2 port / Goonies 20th anniversary etc.?
i know they are pre-installed, just in case to remove them and install them again after.
Thanks

**Comment by retr0rangepi** [comment]
original RetroPie ports can be removed/installed using the RetroPie-Setup (some may not work after reinstalled, needs some test). Easy alternative is to remove the whole ports folder from ~/RetroPie/roms if you dont want the Ports section showing on EmulationStation. For the time being, you can also move/remove specific files somewhere else and move them back when you want.
