### ISSUE TITLE
Struck in Kernel

### ISSUE THREAD

**Issue by TheKayneGame** [retr0rangepi/RetrOrangePi#18]
MY system is stuck in kernel im running latest retrorangepi. it works when connected to usb but not when getting 5v from bench psu.

**Comment by retr0rangepi** [comment]
which board? Try a more reliable 5V PSU, usually 2A minimum is required

**Comment by TheKayneGame** [comment]
Orange Pi Zero Plus 2 H3, and it works them i'm just connected to an USB adaptor But it does not work when i connect it to the 5v pins. The Device comes to life, it tries to do the u boot stuff but gets stuck with UBS Bus

**Comment by retr0rangepi** [comment]
I cannot reproduce this issue. My ZeroPlus2 H3 works fine from pins 1 and 2 (5V and GND).

**Comment by TheKayneGame** [comment]
![jpeg_20180226_185759](https://user-images.githubusercontent.com/5954012/36686574-26c15654-1b27-11e8-892b-3ec8848e69bd.jpg)
This is the result i get when i connect to pin 1 and 2. waiting does no good...

**Comment by alerinoreis** [comment]
This behavior is similar to booting with analog TV settings, HDMI  source is active and cable is present 
Otherwise, still not reproducible

**Comment by retr0rangepi** [comment]
![img_0966](https://user-images.githubusercontent.com/31192446/36765513-621a8128-1c10-11e8-9c09-30d9b655001a.JPG)
