### ISSUE TITLE
The eMMC isn't visible as block device on Orange Pi Plus 2e

### ISSUE THREAD

**Issue by lictw** [retr0rangepi/RetrOrangePi#20]
Hello! 

I don't see the eMMC in /dev/mmc* on my Orange Pi Plus 2e. There is only the SD card and its partitions. But the eMMC is visible on the clear armbian. Is it my local problem or an OS' bug? Thanks!

**Comment by retr0rangepi** [comment]
probably both, depending on the state of the OS, eMMC is detected. In this forum thread, there's some useful, maybe a fix for you. Please test and let us know.

**Comment by lictw** [comment]
Hi!

When i copied the entire /boot from the lateast armbian (all files with override, from clean ISO, not from my eMMC installation) to /boot section of ROPi, exlude zImage and uInitrd files, my board starts to load into the armbian from eMMC. 

I think i do something wrong.. It's hard for me to understand what i'm doing, since this is my first single-board computer. And the boot process is very different from classic PCs.

**Comment by lictw** [comment]
Well, i'll try and write here about the results.

**Comment by retr0rangepi** [comment]
this is supposed to be fixed in the new release (v4.2 SLIM) 
http://www.retrorangepi.download/download/index2.html
