### ISSUE TITLE
Mali-450 GPU for OrangePi Zero Plus 2 H5

### ISSUE THREAD

**Issue by vgoffman** [retr0rangepi/RetrOrangePi#22]
Hi! Is this that driver you need for OrangePi Zero Plus 2 H5 to build new image RertOrangPi for OrangePi Zero Plus 2 H5?

https://developer.arm.com/products/software/mali-drivers/utgard-kernel#

**Comment by retr0rangepi** [comment]
Not only that one, it would need kernel configuration, beyond us.
