### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by davidhernandeze** [retr0rangepi/RetrOrangePi#26]
I have an orangepi lite, is it compatible with retroOrangePi?

**Comment by retr0rangepi** [comment]
regular Orange Pi Lite yes
http://www.retrorangepi.org/images/4.1/full/RetrOrangePi-4.1.Orangepilite.img.tar.gz

Orange Pi Lite no, no compatible drivers available

**Comment by huangda1982** [comment]
I have a banana pi m1+, it is compatible with retroOrangePi?

**Comment by retr0rangepi** [comment]
no it isn't. Only Banana Pi M2+ and M2 zero
