### ISSUE TITLE
FPS Drops whith two pcb from Brook are conected

### ISSUE THREAD

**Issue by thallestorchi** [retr0rangepi/RetrOrangePi#28]
when using two or more controls (with UNIVERSAL FIGHTING BOARD from Brook LLC http://www.brookaccessory.com/Fighting%20Board/list.html) FPS drops a lot on all core emulators

**Comment by retr0rangepi** [comment]
how do you connect this to the orange pi? If it's USB, try a self powered hub in between

**Comment by thallestorchi** [comment]
hello the controls are connected by usb. I'll do the test by connecting a power hub. Then post the results later.
