### ISSUE TITLE
WiFi Not working on Banana Pi M2+ Zero

### ISSUE THREAD

**Issue by withgallantry** [retr0rangepi/RetrOrangePi#29]
Wifi isn't working on the Banana Pi M2 Zero with the RetrOrangePi 4.2 SLIM Image. 
Setting the wifi manually in /etc/network/interfaces using the below does not work. Making it impossible to install things such as GPIO controls. 
```
source /etc/network/interfaces.d/*
    allow-hotplug wlan0
    auto wlan0
    iface wlan0 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```

**Comment by retr0rangepi** [comment]
Interfaces file is ignored by NetworkManager, looks like a latest Armbian update broke DNS resolving, still troubleshooting

**Comment by retr0rangepi** [comment]
try this:
wget http://www.retrorangepi.org/interfaces (or check the file syntax and change accordingly, so the interface is correct, its oddly named as "wlan2")
sudo cp interfaces /etc/network
sudo service network-manager restart
sudo ifconfig eth0 down
