### ISSUE TITLE
Start EmulationStation from command

### ISSUE THREAD

**Issue by Liontek1985** [retr0rangepi/RetrOrangePi#33]
Hello

It is not possible without the complete path to start ES
In all versions before v4 its possible to run from command ES with "emulationstation"

please add a script or shortcut to start fast from command to ES

**Comment by retr0rangepi** [comment]
Will do, but Ctrl D works

**Comment by Liontek1985** [comment]
I have to test it thanks
is it possible to change the shortcut on other keys?
a script in "retropiemenu/retrorangepi" to switch would be great

**Comment by Liontek1985** [comment]
works thx
