### ISSUE TITLE
[feature request] mount scrape and run from USB

### ISSUE THREAD

**Issue by Tom-Neverwinter** [retr0rangepi/RetrOrangePi#4]
mount scrape and run from USB. this is a feature that works on lakka and retropi, but on this rom the only way it works is to move things to the root partition.

**Comment by retr0rangepi** [comment]
did you update to 4.0 version? usbromservice like retropie is up and working.

**Comment by retr0rangepi** [comment]
usbromservice confirmed working by some other users.
