### ISSUE TITLE
Please add lr-scummvm to ROPI

### ISSUE THREAD

**Issue by Dahak66** [retr0rangepi/RetrOrangePi#41]
In the current version of RetroPie there's an experimental package for lr-scummvm (libretro/retroarch version of scummvm). This version is much friendlier to systems without analogue controllers (e.g., Retrostone) than the vanilla scummvm package.

**Comment by retr0rangepi** [comment]
Added https://github.com/retr0rangepi/RetroPie-Setup/commit/f18d8e58086343064d3fa66459d6cd00a1d0923c . 
Please run RetroPie-Setup, Update script to the latest version, then run lr-scummvm from Experimental Packages. It takes really long (almost two hours) to compile, make sure your retrostone is charged.

**Comment by retr0rangepi** [comment]
i'm at work now, i only run it from command line, please test and let us know

**Comment by Dahak66** [comment]
Tried running Loom and Fate of Atlantis using copies that work on Retropie version of lr-scummvm. On ROPI version, it recognises the svm folder correctly, but goes straight back to ES after failing to launch.

**Comment by retr0rangepi** [comment]
i ran the libretro core from command line, added Kings Quest 5 and it ran normally. I'll have to check if there is any windowing issue with the Retrostone or you have to readd the games and generate new .svm entries.

**Comment by qu1que** [comment]
Hi, I've tried to install lr-scummvm on the Retrostone following your instructions (updating retropie-script and going to experimental packages). I have the following error: 
![captura de pantalla de 2019-01-30 20-41-15](https://user-images.githubusercontent.com/39677257/52009229-b7fc2d00-24d2-11e9-8242-51f0d0ec495e.png)

And this is the log for that error:

[rps_2019-01-30_204028.log](https://github.com/retr0rangepi/RetrOrangePi/files/2814247/rps_2019-01-30_204028.log)

What could be wrong?

**Comment by retr0rangepi** [comment]
Patch 01_fix_quit.diff failed to apply , very strange , maybe you can edit lr-scummvm.sh and remove the patch from file or the patch itself

**Comment by qu1que** [comment]
Thanks! It seems that is working now!! I comment this line in the lr-scummvm.sh script: 

#applyPatch "$md_data/01_fix_quit.diff"

Now it's compiling

EDITED: It works now!

**Comment by retr0rangepi** [comment]
tested fine, will feature next release.
