### ISSUE TITLE
Retroarch won't launch over retropie menu

### ISSUE THREAD

**Issue by Liontek1985** [retr0rangepi/RetrOrangePi#42]
Retroarch won't launch over retropie menu

Hello Guys,

I have updated retropie script and then retroarch, now i can´t launch retroarch over retropiemenu
after reflashing the sd card i have make the same stepps and have the self effect...

over emulationstation i can launching games with lr-emulators without problems, only over retropiemenu i cant start it. I see no error only black screen and fallback to retropiemenu

i have test the update with version 1.7.5 and 1.7.6 the same problem
i think is a installation/update script problem

1.) flash sh install ropi 4.2
2.) update retropie script
3.) update armbian system update upgrade
4.) update retroarch

i have tested without update armbian system the same problem

i see no errors, no command.log entrys
looks like the retroarch start script cant launch it without a game

best regards fredy

**Comment by retr0rangepi** [comment]
cannot reproduce this with v1.7.6, Retroarch runs fine standalone from ES. 
What are your steps to update Retroarch?

**Comment by Liontek1985** [comment]
Retropie setup, core packages, retroarch, update from source

ROPI 4.2 FULL ORANGEPIPC

have you tested with 4.2 or with mainline?

**Comment by Liontek1985** [comment]
error fixed, is in retropie-setup -> closed

how you can fix? update the joy2key.py
i have manualy fork from original retropie-setup for pi3, manual edits in some files necessary

**Comment by asiapool** [comment]
pi4 4.7.1  cant start retroarch confirmed
