### ISSUE TITLE
Kodi stops to work after install kodi-pvr-iptvsimple via CLI/SSH

### ISSUE THREAD

**Issue by hpandelo** [retr0rangepi/RetrOrangePi#53]
If you try to install the simple-pvr-client from repo using `apt install kodi-pvr-iptvsimple` it will suggest you to "upgrade" kodi to the repo version. 

But after this installation done, you can't access kodi anymore returning the message: `ERROR: Unable to create GUI. Exiting`

How to use repo version of kodi?
If isn't possible, have a way to compile kodi and the addons directly from kodi repo??

**Comment by retr0rangepi** [comment]
Repo version cannot be used as it's built to work on X11. We've compiled GBM version of Kodi. 

Instructions:
Quit Emulationstation (F4)
cd
wget http://www.retrorangepi.org/addons.tar.gz
sudo tar -zxvf addons.tar.gz -C /usr/share/kodi/addons/   (case sensitive)
Go to settings - add-ons - PVR clients - IPTV Simple - Enable
