### ISSUE TITLE
Kodi 18.4 Leia

### ISSUE THREAD

**Issue by macchese-eng** [retr0rangepi/RetrOrangePi#57]
Is it possible to have 18.4 Leia as version of Kodi? With the 19 Alpha it is impossible to load the addons, and I was interested in how the tvheadend works Thanks and congratulations for the work done

**Comment by retr0rangepi** [comment]
addons work on kodi 19 as well.



Instructions:

Quit Emulationstation (F4)
cd
wget http://www.retrorangepi.org/addons.tar.gz
sudo tar -zxvf addons.tar.gz -C /usr/share/kodi/addons/ 
(case sensitive)
Includes: peripheral.joystick (gamepad input support), pvr.iptvsimple and pvr.hts (headend)

For IPTV , you'll have to go to settings - add-ons - PVR clients -  Enable

![image](https://user-images.githubusercontent.com/31192446/69008833-b7336b00-092d-11ea-9177-0d3150caf7b1.jpg)

**Comment by macchese-eng** [comment]
I have only pvr-iptv...no Tvheadend Thanks

**Comment by retr0rangepi** [comment]
you mentioned tvheadend , anyway iptvsimple should work for you

**Comment by macchese-eng** [comment]
Thanks anyway. But as pvr I use tvheadend for a TV that has no possibility of terrestrial antenna. I will wait for new updates. Thanks again for the job done
