### ISSUE TITLE
RetrOrangePi 4.3 segfaults after system update on OrangePI PC 2

### ISSUE THREAD

**Issue by SiliconVampire** [retr0rangepi/RetrOrangePi#58]
While I've been informed that RetrOrangePi for the OrangePi PC 2 is in beta and to not do a system upgrade, the same person said to create a ticket and upload my log from my update.  From a fresh install I did the following:

sudo apt update
sudo apt upgrade

Once that was done I rebooted the Pi.  When it booted up, the initial splash screen plays as normal.  It then drops me to a terminal with a simple "Segfault" followed by a prompt.  I can get into Armbian desktop, but RetrOrangePi will not boot up.  I've attached my dpkg.log so you can see what files were updated

[dpkg.log](https://github.com/retr0rangepi/RetrOrangePi/files/3873081/dpkg.log)

**Comment by retr0rangepi** [comment]
segfault seems to be gone in the last 64bits beta
