### ISSUE TITLE
No video in kodi using Orange Pi Zero or analog output with hw acceleration (MPV+VDPAU)

### ISSUE THREAD

**Issue by nixenos** [retr0rangepi/RetrOrangePi#6]
Yet another trouble on my OrangePI Zero. When I want to run a movie from pendrive or from yt it only plays sound, no video or controls at all.

**Comment by retr0rangepi** [comment]
right click on video and choose Play with Internal Player, not MPV , which needs a special parameter to run on non-HD resolutions, will work on a fix to work with MPV (hardware accelerated)

**Comment by nixenos** [comment]
Will try it in a second. Is there a way to do it using Xbox 360 pad?

**Comment by retr0rangepi** [comment]
yes, one of the buttons should be right-click

**Comment by nixenos** [comment]
Okay, I figured it out how to do it. 
Now it works, thanks! Unfortunately 720p is too much for opi zero, it shutters as hell but works!

**Comment by retr0rangepi** [comment]
i'm reopening so i can add an out-of the-box solution

**Comment by nixenos** [comment]
Okay
Well I wonder if there's a trick or anything that would allow me to watch at least 480p videos shutterless, but I think there's no way, Mali is not powerful enough

**Comment by retr0rangepi** [comment]
wait for a fix to use MPV instead. Strange that i watch IPTV with internal player without any stuttering

**Comment by retr0rangepi** [comment]
edit ~/.kodi/userdata/playercorefactory.xml and replace --vo=vdpau by --vo=x11
