### ISSUE TITLE
How-to self compile from scratch a retroorangepi image

### ISSUE THREAD

**Issue by dpeddi** [retr0rangepi/RetrOrangePi#60]
Hi,

I'm looking for an how-to build from scratch the retroorangepi image.

Regards

**Comment by retr0rangepi** [comment]
Still no detailed howto, but you can begin with:

1. compile Armbian - https://github.com/armbian/build 
2. compile Mali module - https://github.com/mripard/sunxi-mali
3. fetch Mali userspace libraries and headers - https://github.com/bootlin/mali-blobs
4. compile SDL2 with KMS backend - https://github.com/spurious/SDL-mirror
5. fetch RetrOrangePi and RetroPie-Setup repositories from https://github.com/retr0rangepi
6. Run RetroPie-Setup and build basic packages and the emulator cores you want
7. create a symbolic link from RetrOrangePi to /home/pi/RetroPie/retropiemenu/

If compilation fails, open an issue with full detailed logs stored in /home/pi/RetroPie-Setup/logs/
