### ISSUE TITLE
Screen color saturation very off; Needs saturation controls

### ISSUE THREAD

**Issue by SolvalouArt** [retr0rangepi/RetrOrangePi#63]
The screen itself looks great but any color from yellow to red looks brown and desaturated. There should be a way to adjust this. 

An example showing the RetroStone 2 on the left and my laptop on the right, displaying the same game. 
![IMG_20200127_202707__01](https://user-images.githubusercontent.com/36186620/73613691-03955b00-45ad-11ea-875a-d292b64f28a4.jpg)

**Comment by retr0rangepi** [comment]
http://orangepi.club/showthread.php?tid=3393&pid=9198#pid9198
