### ISSUE TITLE
Where is compotable buttons list

### ISSUE THREAD

**Issue by UncleJey** [retr0rangepi/RetrOrangePi#64]
Hi everyone!
wanna add GPIO with large single joystick
where i can find compotable buttons codes?

**Comment by retr0rangepi** [comment]
Python script is here: 
https://github.com/retr0rangepi/RetrOrangePi/blob/mainline/GPIO/drivers/tz_gpio_controller.py

GPIO controller can be enabled from EmulationStation - RetroPie - RetrOrangePi - Enable GPIO option
