### ISSUE TITLE
mesa-common-dev craching emulationstation

### ISSUE THREAD

**Issue by mzramna** [retr0rangepi/RetrOrangePi#68]
I’m trying to add some extras to orangepi pc plus, but there’s always a lack of a mesa driver application that doesn’t let the extras be installed, any how to fix this? if i install the expecificaly application the emulationstation stops working and acuses permission dained

when i try to install any of the ports into the opt category like `solarus` it cannot be installed because of the missing application,and enter into an dependency hell since i install it manually

the specific application is:

> mesa-common-dev_19.0.8-0ubuntu0~18.04.1_armhf
wich i've installed using the .deb file

on system boot emulationstation launching error after installing library:
`/opt/retropie/configs/all/autostart.sh: line 21: /opt/retropie/supplementary/emulationstation-dev/emulationstation.sh: no such file or directory`

on running `emulationstation` command error after installing library on ssh:
`emulaionstation: command not found`

on running `emulationstation` command error after installing library on actual machine:
`/opt/retropie/supplementary/emulationstation/emulationstation.sh: 6: /opt/retropie/supplementary/emulationstation/emulationstation.sh: /opt/retropie/supplementary/emulationstation/emulationstation: Permission denied`

using latest img file on sd

**Comment by retr0rangepi** [comment]
`sudo apt-mark unhold libsdl2-dev libgl1* libegl* libgles* libgbm* libwayland-egl*`

they were put on hold to avoid system dependencies being messed up
report any bug
