### ISSUE TITLE
Compile kernel(RetrOrangePi_4.2_FULL_Armbian_5.59)

### ISSUE THREAD

**Issue by Lyric1984** [retr0rangepi/RetrOrangePi#72]
Hi,
I downloaded a firmware:(http://www.retrorangepi.org/FULL/RetrOrangePi_4.2_FULL_Armbian_5.59_Orangepilite_Debian_jessie_default_3.4.113_desktop.7z)
I need to modify the kernel, where to download the corresponding source code to compile?

**Comment by retr0rangepi** [comment]
Kernel source: https://github.com/armbian/linux  , branch sun8i
Older build tools and patches: https://github.com/armbian/build/tree/1c11d6ff58301d87640ebcbaa915861219039719
keep in mind v4.2 is based on kernel 3.4.113 and debian jessie, not supported anymore
