### ISSUE TITLE
Support for Orange Pi 2 Plus

### ISSUE THREAD

**Issue by grawi-sikorsky** [retr0rangepi/RetrOrangePi#75]
Hi! Sadly image for Orange Pi 2E Plus is not working with **Orange Pi 2 Plus**.
Seems everything is ok except USB ports which are disabled (no power, no keyboard, gamepad etc.)
Is it possible to tweak it? Make USB ports working?

Best regards!
J.

**Comment by retr0rangepi** [comment]
please try this: https://github.com/retr0rangepi/RetrOrangePi/issues/70#issuecomment-624573344
