### ISSUE TITLE
OPI4 rk3399 on mainline

### ISSUE THREAD

**Issue by ghost** [retr0rangepi/RetrOrangePi#82]
Hi buddy! 
I am interested on make a video about this due it's based on armbian.. but I need panfrost. 
first, I dont see any build for opi4 and second, I need to know if it does run on mainline with panfrost, bc that is what I am looking for.. for other reasons. 

thanks!

**Comment by retr0rangepi** [comment]
No opi 4 board here , so no image for it. Tried panfrost successfully on opi one plus (H6), but there are some caveats, image still in the works

**Comment by ghost** [comment]
Orabge po didnt send you a board?? Thats ridiculous. Oka. I will try to boot it anyway.
