### ISSUE TITLE
Image for Orange Pi Zero on the website missing

### ISSUE THREAD

**Issue by rumpeltizkin** [retr0rangepi/RetrOrangePi#9]
Hello;

I can't find the image for the Orange Pi Zero. It says "coming soon" for the 4.1 but it does not allow me to download the 3.0.1 version anymore.

I don't want to wait for the "coming soon" if it's going to take weeks, I want to start running 3.0.1. Any mirror where I can download it?

Thank you.

**Comment by retr0rangepi** [comment]
http://www.retrorangepi.org/OLDSITE/images/3.0.1/

**Comment by rumpeltizkin** [comment]
Thank you! :D
